# Generated by Django 3.1.7 on 2021-03-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='posta_code',
            new_name='postal_code',
        ),
    ]
